#define CONNECT		0
#define WAIT		1
#define DISCONNECT	2
#define DEAL		3
#define ASK		4
#define PLAY		5
#define GIVE		6
#define EMPTY		7
#define ROUND		8
#define SCORE		9
#define SCORES		10
#define WINNER		11 
